# Generated by Django 4.1.4 on 2023-02-21 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='charSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('character_class', models.CharField(max_length=45)),
                ('level', models.IntegerField()),
                ('charStr', models.IntegerField()),
                ('charDex', models.IntegerField()),
                ('charCon', models.IntegerField()),
                ('charInt', models.IntegerField()),
                ('charWis', models.IntegerField()),
                ('charCha', models.IntegerField()),
                ('items', models.JSONField()),
                ('max_hp', models.IntegerField()),
                ('current_hp', models.IntegerField()),
                ('feats', models.JSONField()),
                ('initiative', models.IntegerField()),
                ('alignment', models.CharField(choices=[('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil'), ('LE', 'Lawful Evil'), ('NN', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('LN', 'Lawful Neutral'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LG', 'Lawful Good')], default='NN', max_length=16)),
                ('background', models.TextField()),
                ('race', models.CharField(max_length=40)),
                ('exp', models.IntegerField()),
                ('language_proficiency', models.TextField()),
                ('weapon_proficiency', models.JSONField()),
                ('armor_proficiency', models.JSONField()),
                ('attack_options', models.JSONField()),
                ('misc_features', models.JSONField()),
                ('spells_known', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
