# Generated by Django 4.1.4 on 2023-02-28 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="charSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_name", models.CharField(max_length=45)),
                ("character_class", models.CharField(max_length=45)),
                ("level", models.IntegerField(default=1)),
                ("charStr", models.IntegerField(default=10)),
                ("charDex", models.IntegerField(default=10)),
                ("charCon", models.IntegerField(default=10)),
                ("charInt", models.IntegerField(default=10)),
                ("charWis", models.IntegerField(default=10)),
                ("charCha", models.IntegerField(default=10)),
                ("items", models.JSONField(blank=True, null=True)),
                ("max_hp", models.IntegerField(default=1)),
                ("current_hp", models.IntegerField(default=8)),
                ("feats", models.JSONField(blank=True, null=True)),
                ("initiative", models.IntegerField(default=0)),
                (
                    "alignment",
                    models.CharField(
                        choices=[
                            ("NE", "Neutral Evil"),
                            ("CE", "Chaotic Evil"),
                            ("LE", "Lawful Evil"),
                            ("NN", "True Neutral"),
                            ("CN", "Chaotic Neutral"),
                            ("LN", "Lawful Neutral"),
                            ("NG", "Neutral Good"),
                            ("CG", "Chaotic Good"),
                            ("LG", "Lawful Good"),
                        ],
                        default="NN",
                        max_length=16,
                    ),
                ),
                (
                    "background",
                    models.TextField(
                        blank=True, default="Orphan who grew up on a farm..."
                    ),
                ),
                ("race", models.CharField(max_length=40)),
                ("exp", models.IntegerField(default=0)),
                ("language_proficiency", models.TextField(blank=True)),
                ("weapon_proficiency", models.JSONField(blank=True, null=True)),
                ("armor_proficiency", models.JSONField(blank=True, null=True)),
                ("attack_options", models.JSONField(blank=True, null=True)),
                ("misc_features", models.JSONField(blank=True, null=True)),
                ("spells_known", models.JSONField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
