# Generated by Django 4.1.4 on 2023-03-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charsheet",
            name="diety",
            field=models.CharField(default="Pelor", max_length=45),
        ),
        migrations.AddField(
            model_name="charsheet",
            name="hit_dice",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="charsheet",
            name="saves",
            field=models.ManyToManyField(
                blank=True,
                choices=[
                    ("str", "Strength"),
                    ("dex", "Dexterity"),
                    ("con", "Constitution"),
                    ("wis", "Wisdom"),
                    ("int", "Intelligence"),
                    ("cha", "Charisma"),
                ],
                to="characters.charsheet",
            ),
        ),
        migrations.AddField(
            model_name="charsheet",
            name="temp_hp",
            field=models.IntegerField(default=0),
        ),
    ]
