# Generated by Django 4.1.4 on 2023-03-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "characters",
            "0002_charsheet_diety_charsheet_hit_dice_charsheet_saves_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charsheet",
            name="saves",
        ),
    ]
