# Generated by Django 4.1.4 on 2023-02-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_rename_title_charsheet_char_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charsheet',
            name='armor_proficiency',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='attack_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='feats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='language_proficiency',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='misc_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='spells_known',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='weapon_proficiency',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
