# Generated by Django 4.1.4 on 2023-02-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_charsheet_armor_proficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charsheet',
            name='background',
            field=models.TextField(blank=True, default='Orphan who grew up on a farm...'),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='charCha',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='charCon',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='charDex',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='charInt',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='charStr',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='charWis',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='current_hp',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='initiative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='charsheet',
            name='max_hp',
            field=models.IntegerField(default=1),
        ),
    ]
