# Generated by Django 4.1.4 on 2023-03-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_charsheet_save_proficiencies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charsheet",
            name="save_proficiencies",
        ),
        migrations.AddField(
            model_name="charsheet",
            name="charisma_proficiency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charsheet",
            name="constitution_proficiency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charsheet",
            name="dexterity_proficiency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charsheet",
            name="intelligence_proficiency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charsheet",
            name="strength_proficiency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="charsheet",
            name="wisdom_proficiency",
            field=models.BooleanField(default=False),
        ),
    ]
