# Generated by Django 4.1.4 on 2023-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_remove_charsheet_save_proficiencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charsheet',
            name='natural_armor',
            field=models.IntegerField(default=0),
        ),
    ]
