# Generated by Django 4.1.4 on 2023-03-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_charsheet_natural_armor'),
    ]

    operations = [
        migrations.AddField(
            model_name='charsheet',
            name='speed',
            field=models.IntegerField(default=30),
        ),
    ]
