# Generated by Django 4.1.4 on 2023-03-30 09:26

import characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_charsheet_character_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='charsheet',
            name='classes',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[characters.models.validate_classes]),
        ),
    ]
