# Generated by Django 4.1.4 on 2023-03-30 10:25

import characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_charsheet_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charsheet',
            name='classes',
            field=models.JSONField(blank=True, default={'class1': {'level': 10, 'name': 'Wizard'}, 'class2': {'level': 10, 'name': 'Barbarian'}}, null=True, validators=[characters.models.validate_classes]),
        ),
    ]
