# Generated by Django 4.1.4 on 2023-04-04 03:31

import characters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_alter_charsheet_character_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charsheet',
            name='classes',
            field=models.JSONField(blank=True, default=characters.models.get_default_class, null=True, validators=[characters.models.validate_classes]),
        ),
    ]
